theme = "gruvbox_dark_hard"

[editor]
mouse = true
bufferline = "always"
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal.g]
a = "code_action"

[keys.normal]
C-s = ":w"
C-k = ":buffer-next"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert.j]
k = "normal_mode"