# ~/.config/helix/config.toml


theme = "gruvbox"
# theme = "nord"

[editor]
mouse = false
#bufferline = "multiple"
line-number = "absolute"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
ret = ["open_below", "normal_mode"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.g]
a = "code_action" # Maps 'ga' to show possible code actions

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }


[keys.normal."+"]
m = ":run-shell-command make"
r = ":run-shell-command cargo run"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"