#! /bin/zsh

export DOTFILES="$HOME/dotfiles"
export PERSONAL="$HOME/personal"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export EDITOR="helix"
export VISUAL="helix"

# X11
# export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# PATH
export PATH="$PATH:$HOME/.cargo/bin"

export BUN_INSTALL="$HOME/.bun"
export PATH="$PATH:$BUN_INSTALL/bin"
